[tool.poetry]
package-mode = false
authors = ["Vitalii Morskyi <vitalii@morskyi.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
jupyterlab = "^4.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
